In [2]:
import numpy as np
#assign the input values
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [ ]:
#assign the output values

In [3]:
output = np.array([0,1,1,0])
output = output.reshape(4,1)
output.shape

(4, 1)

In [ ]:
#assign our weights

In [4]:
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [ ]:
#now the bias(which is a constant)

In [5]:
bias = 0.3

In [6]:
#need an activation function(here we use sigmoid function)

In [7]:
def sigmoid_func(x):
    return 1/(1+ np.exp(-x))

In [8]:
#derivative of the sigmoid function

In [9]:
def der(x):
    return sigmoid_func(x)*(1-sigmoid_func(x))

In [10]:
#training/ updating our weights

In [11]:
for epochs in range(10000):
    input_arr = input_value
    bias = 0.3
    weighted_sum =np.dot(input_arr, weights) + bias
    first_output = sigmoid_func(weighted_sum)
    
    error = first_output - output
    total_error = np.square(np.subtract(first_output, output)).mean()
    #print(total_error) If you print this we get a long list of error calulations 
    
    first_der = error
    second_der = der(first_output)
    derivative = first_der*second_der
    
    t_input = input_value.T
    final_derivative = np.dot(t_input,derivative)
    
    #UPDATE our weights
    weights = weights - 0.05 *final_derivative
    
    #update the bias
    for i in derivative:
            bias = bias-0.05*i
            
print(weights)#in array brackets
print(bias)

[[-4.02755172]
 [ 7.64343377]]
[0.29328441]


In [13]:
#predictions
pred = np.array([0,1])
#^ the output for this input should be 1, so the output(the print statement) should be close to 1.
result = np.dot(pred, weights)+bias

pred2 = np.array([1,0])
result2 = np.dot(pred2, weights)+bias

res = sigmoid_func(result)
res2 = sigmoid_func(result2)
print(res)
print(res2)

[0.99964275]
[0.02333322]
